package lexico;

public enum TipoToken {
    IDENTIFICADOR,
    NUMERO_ENTERO,
    NUMERO_DECIMAL,
    CADENA,
    PALABRA_RESERVADA,
    SIMBOLO,
    SIMBOLO_COMPUESTO,
    SIMBOLO_ASSIGN,
    SIMBOLO_COMPARISON,
    OP_ARITMETICO
}